{
	"version": 1528820561,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/turret-sheet0.png",
		"images/bullet1-sheet0.png",
		"images/bullet1-sheet1.png",
		"images/alienship1-sheet0.png",
		"images/spawnpoint1-sheet0.png",
		"images/mainbackgound-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/explosion1.png",
		"images/sprite3-sheet0.png",
		"images/stars-sheet0.png",
		"images/nebula-sheet0.png",
		"images/spawnpoint2-sheet0.png",
		"images/spawnpoint3-sheet0.png",
		"images/spawnpoint4-sheet0.png",
		"images/spawnpoint5-sheet0.png",
		"images/alien1particles.png",
		"images/flame0-sheet0.png",
		"images/flame0-sheet1.png",
		"images/light-sheet0.png",
		"images/light-sheet1.png",
		"images/sprite-sheet0.png",
		"images/earth-sheet0.png",
		"images/scrollto-sheet0.png",
		"images/bombexplosion-sheet0.png",
		"images/bomb-sheet0.png",
		"images/shrapnel.png",
		"media/lazer fire 1.m4a",
		"media/lazer fire 1.ogg",
		"media/lazer fire 2.m4a",
		"media/lazer fire 2.ogg",
		"media/explosion 5.m4a",
		"media/explosion 5.ogg",
		"media/startup3.m4a",
		"media/startup3.ogg",
		"media/explosion 4.m4a",
		"media/explosion 4.ogg",
		"media/retrolaser2.m4a",
		"media/retrolaser2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}